language: python
python:
  - "3.7.3"
install:
  - pip3 install homeassistant
  - pip3 install appdaemon
script:
  - hass -c . --script check_config
before_install:
  - mv secrets.yaml.example secrets.yaml
