#**********************************************************
#* CATEGORY    CONFIG
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright (C) 2017  Haynie Research & Development

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License along
#with this program; if not, write to the Free Software Foundation, Inc.,
#51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

#**********************************************************
#* BASE CONFIG
#**********************************************************
homeassistant:
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation
  name: Home
  temperature_unit: F
  time_zone: America/Denver
  unit_system: imperial
  customize: !include config/customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret base_url
  trusted_networks:
    - 127.0.0.1
    - !secret base_ip

logger:
  default: error
  logs:
    homeassistant.components.device_tracker: error
    homeassistant.components.shell_command: debug

logbook:
  include:
    domains:
      - automation
      - alarm_control_panel
      - scene
  exclude:
    domains:
      - sun
      - device_tracker
      - group
      - climate
    entities:
      - sensor.kitchen_proximity
      - binary_sensor.kitchen_presence
      - sensor.master_bedroom_proximity
      - binary_sensor.master_bedroom_presence
      - sensor.upstairs_hallway_proximity
      - binary_sensor.upstairs_hallway_presence
      - sensor.hudsons_room_proximity
      - binary_sensor.hudsons_room_presence
      - sensor.wesleys_room_proximity
      - binary_sensor.wesleys_room_presence
      - sensor.average_load_15m
      - sensor.average_load_1m
      - sensor.average_load_5m
      - sensor.cpu_use
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_wind_speed
      - sensor.pws_pressure_in
      - sensor.pws_relative_humidity
      - sensor.pws_temp_f
      - sensor.pws_weather
      - sensor.pws_wind_string
      - sensor.ram_use
      - sensor.time__date

history:
  include:
    entities:
      - climate.downstairs
      - sensor.average_down_temp
      - climate.upstairs
      - sensor.average_up_temp
      - sensor.average_home_temp
      - input_boolean.hvacautomation
      - input_boolean.lancefirecall
      - input_boolean.panic
      - input_select.alarmstatus
      - input_select.homestatus
      - sensor.kitchen_humidity
      - sensor.kitchen_temperature
      - sensor.master_bedroom_humidity
      - sensor.master_bedroom_temperature
      - sensor.upstairs_hallway_humidity
      - sensor.upstairs_hallway_temperature
      - switch.hudsontv
      - switch.wesleytv
      - input_boolean.coalarm
      - input_boolean.firealarm
      - input_boolean.garage_alarm
      - sensor.pws_temp_f
      - sensor.pws_relative_humidity
      - switch.hudsons_fan
      - switch.wesleys_fan
      - sensor.hudsons_room_temperature
      - sensor.wesleys_room_temperature
      - sensor.hudsons_room_humidity
      - sensor.wesleys_room_humidity
      - sensor.livingroom_harmony
      - alarm_control_panel.home_alarm

recorder:
  purge_interval: 7
  purge_keep_days: 14
  db_url: sqlite:///opt/jarvis/database/jarvis.db
  exclude:
    domains:
      - sun

updater:
frontend:
config:
zeroconf:
wemo:
discovery:
shopping_list:
conversation:
alexa:
snips:
dialogflow:

#**********************************************************
#* ACCOUNTS
#**********************************************************
wink:
  local_control: true

twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

climate:
  platform: honeywell
  username: !secret honeywell_user
  password: !secret honeywell_pass
  region: us
  scan_interval: 600
  cool_away_temperature: 26
  heat_away_temperature: 23

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

ifttt:
  key: !secret ifttt_key

#**********************************************************
#* MISC CONFIG
#**********************************************************
weblink:
  entities:
    - name: Home
      url: http://localhost:8123

hue:
  bridges:
    - host: 10.0.1.202

remote:
  - platform: harmony
    name: Living Room
    host: 10.0.1.203

media_player:
  - platform: itunes
    host: 10.0.1.100
  - platform: roku
  - platform: pandora

notify:
  - name: sms
    platform: twilio_sms
    from_number: !secret twilio_from
  - name: call
    platform: twilio_call
    from_number: !secret twilio_from
  - name: twitter
    platform: twitter
    consumer_key: !secret twitter_consumer_key
    consumer_secret: !secret twitter_consumer_secret
    access_token: !secret twitter_access_token
    access_token_secret: !secret twitter_access_token_secret

#Track the Sun
sun:

emulated_hue:
  host_ip: !secret base_ip
  expose_by_default: true

shell_command:
  command: "{{cmd}}"
  run_sudo: /usr/bin/sudo "{{cmd}}"
  volume: /usr/bin/amixer set PCM "{{cmd}}"%
  tts: /opt/jarvis/scripts/tts.sh "{{message}}"
  bomb_sound: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/missle_explosion.wav
  alarm_sound: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/alarm.wav
  fart_sound: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/fart.wav
  air_raid_sound: /usr/bin/aplay /opt/jarvis/sounds/asound_effects/ir_raid.wav
  ghost_sound: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/ghost.wav
  zombie_sound: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/zombie_brains.wav
  foghorn: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/foghorn.wav
  gunshot: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/gunshot.wav
  siren: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/siren.wav
  bullmastiff: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/bullmastiff.wav
  one_tone: /usr/bin/aplay /opt/jarvis/sounds/tones/one-tone.wav
  two_tone: /usr/bin/aplay /opt/jarvis/sounds/tones/two-tone.wav
  shalom_aleichem: /usr/bin/aplay /opt/jarvis/sounds/shabbat/shalom_aleichem.wav
  lcha_dodi: /usr/bin/aplay /opt/jarvis/sounds/shabbat/lcha_dodi.wav
  kah_ribon: /usr/bin/aplay /opt/jarvis/sounds/shabbat/kah_ribon.wav
  german_shephard: /usr/bin/aplay /opt/jarvis/sounds/sound_effects/german-shephard.wav
  restart_system: /opt/jarvis/scripts/restart_system.sh
  restart_jarvis_base: /opt/jarvis/scripts/restart_jarvis_base.sh
  restart_jarvis_stt: /opt/jarvis/scripts/restart_jarvis_stt.sh
  restart_jarvis_tts: /opt/jarvis/scripts/restart_jarvis_tts.sh

#Alarm Panel
alarm_control_panel:
  - platform: manual
    code: !secret alarm_code
    name: home_alarm
    pending_time: 30
    trigger_time: 900
    disarm_after_trigger: false

#**********************************************************
#* FUNNY SOUNDS
#**********************************************************

#**********************************************************
#* INCLUDES
#**********************************************************
automation: !include config/automations.yaml
intent_script: !include config/intents.yaml
camera: !include config/cameras.yaml
group: !include config/groups.yaml
sensor: !include config/sensors.yaml
switch: !include config/switches.yaml
binary_sensor: !include config/binary_sensors.yaml
scene: !include config/scenes.yaml
input_select: !include config/input_select.yaml
input_boolean: !include config/input_boolean.yaml
input_number: !include config/input_number.yaml
script: !include config/scripts.yaml
panel_custom: !include config/panel_custom.yaml
