title: Jarvis Home Automation
views:
  - title: ''
    path: home
    theme: Dark Theme
    panel: false
    icon: 'mdi:home'
    badges: []
    cards:
      - type: vertical-stack
        gridcols: 180px auto 180px
        cards:
          - type: thermostat
            entity: climate.downstairs
          - type: thermostat
            entity: climate.upstairs
      - type: vertical-stack
        gridcols: 180px auto 180px
        cards:
          - type: alarm-panel
            states:
              - arm_home
              - arm_away
            entity: alarm_control_panel.home_alarm
          - type: entities
            entities:
              - entity: alarm_control_panel.home_alarm
                icon: 'mdi:security'
              - entity: sensor.average_down_temp
              - entity: sensor.average_down_temp
          - type: entities
            entities:
              - entity: switch.restart_system
                name: Restart System
                icon: 'mdi:power'
              - entity: input_select.rule_freq
              - entity: script.leaving_in_15_min
                icon: 'mdi:car'
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.internet_status
          - type: sensor
            entity: sensor.uptime
          - type: sensor
            entity: sensor.processor_use
            graph: line
          - type: sensor
            entity: sensor.memory_use_percent
            graph: line
          - type: gauge
            entity: sensor.load_1m
            min: 0
            name: 1 Minute Load
            max: 4
            severity:
              green: 1
              yellow: 2
              red: 3.5
