#**********************************************************
#* CATEGORY    CAMERAS
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright 2020 Haynie IPHC, LLC
#Developed by Haynie Research & Development, LLC
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.#
#You may obtain a copy of the License at
#http://www.apache.org/licenses/LICENSE-2.0
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

- platform: generic
  name: wxradar
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=ICX&brand=wui&num=1&delay=100&type=NTP&frame=0&scale=1&noclutter=0&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24427697&lat=0&lon=0&label=you%20name:%20RadarGA%20-%20

- platform: ffmpeg
  name: Front Porch
  input: -rtsp_transport tcp -i !secret front_porch_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Back Porch
  input: -rtsp_transport tcp -i !secret back_porch_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Family Room
  input: -rtsp_transport tcp -i !secret family_room_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Living Room
  input: -rtsp_transport tcp -i !secret living_room_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Dining Room
  input: -rtsp_transport tcp -i !secret dining_room_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Kitchen
  input: -rtsp_transport tcp -i !secret kitchen_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Stairs
  input: -rtsp_transport tcp -i !secret stairs_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Upstairs
  input: -rtsp_transport tcp -i !secret upstairs_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Garage
  input: -rtsp_transport tcp -i !secret garage_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Front Yard
  input: -rtsp_transport tcp -i !secret front_yard_cam
  extra_arguments: '-vf "scale=384:216"'

- platform: ffmpeg
  name: Back Yard
  input: -rtsp_transport tcp -i !secret back_yard_cam
  extra_arguments: '-vf "scale=384:216"'
