#**********************************************************
#* CATEGORY    GROUPS
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright 2020 Haynie IPHC, LLC
#Developed by Haynie Research & Development, LLC
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.#
#You may obtain a copy of the License at
#http://www.apache.org/licenses/LICENSE-2.0
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

default_view:
  view: yes
  entities:
    - group.climatefront
    - group.securitysettingsfront
    - group.MiscellaneousFront
    - group.locationswitchfront
    - group.scenesfront
    - group.weather

Lights:
 name: Lights
 view: yes
 entities:
   - group.scenes
   - group.kitchenlights
   - group.livingroomlights
   - group.diningroomlights
   - group.outsidelights
   - group.upstairslights
   - group.masterbedroomlights
   - group.hudsonroomlights
   - group.wesleyroomlights

Climate:
  name: Climate
  view: yes
  entities:
    - group.upstairsclimate
    - group.downstairsclimate
    - group.climateautomation
    - group.hudsonroomclimate
    - group.wesleyroomclimate

Media:
 name: Media
 view: yes
 entities:
   - media_player.pandora
   - group.itunes
   - group.livingroomentertainment
   - group.kidstv
   - group.mediaplayers

Cameras:
  name: Cameras
  view: yes
  entities:
    - camera.wxradar
    - camera.living_room

Security:
  name: Security
  view: yes
  entities:
    - group.securitysettings
    - group.locationswitch
    - group.alllights
    - group.motionsensors
    - group.proximitysensors
    - group.firesensors

Settings:
  name: Settings
  view: yes
  entities:
    - group.misc
    - group.system
    - group.networktest
    - group.serverinfo
    - updater.updater
    - group.all_automations

UpstairsClimate:
  name: Upstairs Climate
  entities:
    - climate.upstairs
    - switch.hudsons_fan
    - switch.wesleys_fan
    - sensor.average_up_temp
    - sensor.upstairs_hallway_temperature
    - sensor.upstairs_hallway_humidity
    - sensor.hudsons_room_temperature
    - sensor.hudsons_room_humidity
    - sensor.wesleys_room_temperature
    - sensor.wesleys_room_humidity

DownstairsClimate:
  name: Downstairs Climate
  entities:
    - climate.downstairs
    - sensor.average_down_temp
    - sensor.kitchen_temperature
    - sensor.kitchen_humidity
    - sensor.master_bedroom_temperature
    - sensor.master_bedroom_humidity

ClimateFront:
  name: Home Climate
  entities:
    - sensor.average_home_temp
    - climate.downstairs
    - sensor.average_down_temp
    - climate.upstairs
    - sensor.average_up_temp

ServerInfo:
  name: Server Information
  entities:
    - sensor.cpu_use
    - sensor.ram_use
    - sensor.average_load_1m
    - sensor.average_load_5m
    - sensor.average_load_15m

Weather:
  - sensor.pws_weather
  - sensor.pws_temp_f
  - sensor.pws_pressure_in
  - sensor.pws_relative_humidity
  - sensor.pws_wind_dir
  - sensor.pws_wind_string
  - sensor.dark_sky_cloud_coverage
  - sensor.dark_sky_hourly_summary
  - sensor.dark_sky_daily_summary

LocationSwitchFront:
  name: Location Switches
  control: hidden
  entities:
    - input_boolean.lancefirecall
    - script.find_katies_iphone
    - script.find_lances_iphone
    - script.find_hudsons_iphone

LocationSwitch:
  name: Location Switches
  control: hidden
  entities:
    - input_boolean.lancefirecall

SecuritySettingsFront:
  name: Security Settings
  entities:
    - alarm_control_panel.home_alarm
    - binary_sensor.smoke_and_co_co_detected
    - binary_sensor.smoke_and_co_smoke_detected
    - input_boolean.garage_hazard

MiscellaneousFront:
  name: Miscellaneous
  entities:
    - input_select.rule_freq
    - script.game_timer
    - script.leaving_in_15_min

SecuritySettings:
  name: Security Settings
  entities:
    - alarm_control_panel.home_alarm
    - input_boolean.panic
    - input_boolean.sound_alarm
    - input_boolean.garage_hazard
    - input_boolean.garage_alarm

ScenesFront:
  name: Lighting
  entities:
    - scene.movies
    - scene.outside_blue
    - scene.patriotic_front_porch
    - scene.outside_bright
    - scene.all_lights_on

Scenes:
  name: Lighting
  entities:
    - scene.movies
    - scene.tv_blue
    - scene.tv_red
    - scene.outside_blue
    - scene.dim_dining_room
    - scene.dim_kitchen
    - scene.patriotic_front_porch
    - scene.all_lights_on

MotionSensors:
  name: Motion Sensors
  entities:
    - binary_sensor.kitchen_presence
    - binary_sensor.master_bedroom_presence
    - binary_sensor.upstairs_hallway_presence
    - binary_sensor.hudsons_room_presence
    - binary_sensor.wesleys_room_presence

ProximitySensors:
  name: Proximity Sensors
  entities:
    - sensor.kitchen_proximity
    - sensor.master_bedroom_proximity
    - sensor.upstairs_hallway_proximity
    - sensor.hudsons_room_proximity
    - sensor.wesleys_room_proximity

FireSensors:
  name: Fire Sensors
  entities:
    - binary_sensor.smoke_and_co_co_detected
    - binary_sensor.smoke_and_co_smoke_detected

NetworkTest:
  name: Network
  entities:
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload

Misc:
  name: Miscellaneous
  entities:
    - script.wesey_tv_automation_bypass
    - input_boolean.nighttimemode
    - input_boolean.flash_hudson_lights
    - input_boolean.flash_wesley_lights
    - input_boolean.hudson_grounded
    - input_boolean.wesley_grounded

System:
  name: System Controls
  entities:
    - script.restart_system
    - script.restart_jarvis_base
    - script.restart_jarvis_stt
    - script.restart_jarvis_tts

ClimateAutomation:
  name: Climate Automation Control
  entities:
    - input_boolean.hvacautomation
    - automation.downstairs_ac
    - automation.downstairs_heat
    - automation.upstairs_ac
    - automation.upstairs_heat

LivingRoomEntertainment:
  name: Living Room Entertainment
  entities:
    - media_player.plex_for_sony_playstation_4_0140
    - media_player.plex_for_vizio_vizio_mtk_2
    - input_select.livingroomharmony
    - input_number.harmonyvolume
    - media_player.pandora
    - input_number.systemvolume

KidsTv:
  name: Kids TVs
  entities:
    - switch.wesleytv
    - switch.hudsontv

MediaPlayers:
  name: Media Players
  entities:
    - media_player.plex_for_vizio_vizio_mtk
    - media_player.wesley_tv
    - media_player.hudson_tv_un40j5200
    - media_player.roku_yu005p719382
    - media_player.lance_office
    - media_player.itunes

KitchenLights:
  name: Kitchen
  entities:
    - light.kitchen
    - switch.pantry_hallway

LivingRoomLights:
  name: Living Room
  entities:
    - light.tv_backlight
    - scene.tv_blue

DiningRoomLights:
  name: Dining Room
  entities:
    - light.dining_room_1
    - light.dining_room_2
    - light.dining_room_3

OutsideLights:
  name: Outside
  entities:
    - light.front_porch_color_1
    - light.front_porch_color_2
    - light.front_porch_color_3
    - light.front_porch_left
    - light.front_porch_right
    - light.back_porch

OutsideColor:
  name: Outside
  entities:
    - light.front_porch_color_1
    - light.front_porch_color_2
    - light.front_porch_color_3
    - light.back_porch

OutsideWhite:
  name: Outside
  entities:
    - light.front_porch_left
    - light.front_porch_right

MasterBedroomLights:
  name: Master Bedroom
  entities:
    - switch.master_closet
    - switch.master_hallway
    - light.master_shower

UpstairsLights:
  name: Upstairs
  entities:
    - switch.upstairs_hallway
    - switch.upstairs_bathroom_main
    - switch.hudsons_light
    - switch.wesleys_light

AllLights:
  name: All Lights
  entities:
    - group.kitchenlights
    - group.livingroomlights
    - group.diningroomlights
    - group.outsidelights
    - group.masterbedroomlights
    - group.upstairslights

AllFans:
  name: All Fans
  entities:
  - switch.hudsons_fan
  - switch.wesleys_fan

AllTemperatureSensors:
  name: All Temperature Sensors
  entities:
    - sensor.master_bedroom_temperature
    - sensor.kitchen_temperature
    - sensor.hudsons_room_temperature
    - sensor.wesleys_room_temperature
    - sensor.upstairs_hallway_temperature

AllPresenseSensors:
  name: All Presence Sensors
  entities:
    - binary_sensor.kitchen_presence
    - binary_sensor.master_bedroom_presence
    - binary_sensor.upstairs_hallway_presence
    - binary_sensor.hudsons_room_presence
    - binary_sensor.wesleyss_room_presence
