#**********************************************************
#* CATEGORY    INPUT BOOLEAN
#* GROUP       HOME AUTOMATION
#* AUTHOR      LANCE HAYNIE <LANCE@HAYNIEMAIL.COM>
#**********************************************************
#Jarvis Home Automation
#Copyright 2020 Haynie IPHC, LLC
#Developed by Haynie Research & Development, LLC
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.#
#You may obtain a copy of the License at
#http://www.apache.org/licenses/LICENSE-2.0
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

hvacautomation:
  name: HVAC Automation
  initial: on
  icon: mdi:thermometer

hudson_grounded:
  name: Hudson Grounded
  initial: off
  icon: mdi:emoticon-sad

wesley_grounded:
  name: Wesley Grounded
  initial: off
  icon: mdi:emoticon-sad

flash_hudson_lights:
  name: Flash Hudson Lights
  initial: off
  icon: mdi:alarm-light

flash_wesley_lights:
  name: Flash Wesley Lights
  initial: off
  icon: mdi:alarm-light

panic:
  name: Panic Alarm
  initial: off
  icon: mdi:alert

sound_alarm:
  name: Sound Alarm
  initial: off
  icon: mdi:alarm-bell

garage_hazard:
  name: Garage Hazard
  initial: off
  icon: mdi:alert-outline

garage_alarm:
  name: Garage Alarm
  initial: off
  icon: mdi:alarm-bell

firealarm:
  name: Fire Alarm
  initial: off
  icon: mdi:fire

coalarm:
  name: Carbon Monoxide Alarm
  initial: off
  icon: mdi:skull

lancefirecall:
  name: Lance on Fire Call
  initial: off
  icon: mdi:fire

livingroomtv:
  name: Living Room TV
  initial: off
  icon: mdi:television-guide

nighttimemode:
  name: Night Time Mode
  initial: on
  icon: mdi:weather-night
